name: IC/CD for backend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
defaults: 
  run: 
    working-directory: "snake-api"


jobs: 
  tests:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
      
      - name: mvn unit test
        run: mvn clean test
        
      # Scan with Trivy
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: ./snake-api
          exit-code: 1 # Pipeline fails if CVE detected
          severity: 'CRITICAL,HIGH'
      
      # Quality Check
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        
  package:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3
      
      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      # Extract metadata from Git reference and GitHub events
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}-api
      
      - name: Build and push Docker backend image
        uses: docker/build-push-action@v6
        with:
          context: snake-api
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install and configure the Koyeb CLI
        uses: koyeb-community/koyeb-actions@v2
        with:
          api_token: "${{ secrets.KOYEB_API }}"
          
      - name: Koyeb Deploy
        run: koyeb service redeploy "involved-alicea/snake-devfest-api"
        
      - name: Set up SSH
        working-directory: ansible
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem
      
      - name: Run Ansible Playbook
        working-directory: ansible
        env:
          ANSIBLE_HOST_KEY_CHECKING: False
        run: ansible-playbook deploy_playbook.yml -i inventories/app.yml -i  "${{ secrets.ANSIBLE_IP }}," -e "ansible_user=${{ secrets.ANSIBLE_USER }}" --private-key private_key.pem